# Programming Assignment 2

## Experiment 2 Numpy Problems

### Normalization Problem

Creates a random 5x5 array and normalizes them using the normalization formula. Then saved as a .npy file.

In [11]:
import numpy as np #imports the numpy library

X = np.random.rand(5, 5) #creates the random 5x5 array

X_normalized = (X - X.mean()) / X.std() #Function for normalization

np.save("X_normalized.npy", X_normalized) #Saves the array

#### Example

In [13]:
#Shows result of the array that was saved. The original and the normalized.
print("Original Array:\n", X)
print("Normalized Array:\n", X_normalized)

Original Array:
 [[0.988539   0.55560186 0.50106403 0.16647939 0.93186089]
 [0.91790088 0.50197843 0.68235937 0.52162278 0.50538084]
 [0.4915776  0.54668533 0.20710494 0.17585595 0.22725411]
 [0.91242602 0.47353194 0.5543618  0.54743013 0.72255604]
 [0.55470561 0.42721525 0.49121794 0.20660229 0.71149471]]
Normalized Array:
 [[ 1.93470719  0.06349044 -0.17222988 -1.61835296  1.68973622]
 [ 1.62939907 -0.16827774  0.61135468 -0.08337202 -0.15357203]
 [-0.2132316   0.02495192 -1.44276347 -1.57782611 -1.35567585]
 [ 1.60573592 -0.29122755  0.05813074  0.02817106  0.78509051]
 [ 0.05961674 -0.49141497 -0.21478614 -1.44493598  0.73728184]]


### Divisible by 3 Problem

Creates 10x10 array that contains the squares of the first 100 positive integers. Then determines all elements that are divisible by 3.

In [17]:
squares = np.arange(1, 101)**2 # Creates a 1d array of the first 100 positive integers and squares them.

A = squares.reshape(10, 10) # Reshapes the 1d array to a 10x10

div_by_3 = A[A % 3 == 0] # Finds elements that are divisible by 3

np.save("div_by_3.npy", div_by_3)

#### Example

In [19]:
#Prints Result
print("Original 10x10 array:\n", A)
print("\nElements divisible by 3:\n", div_by_3)

Original 10x10 array:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
